[package]
name = "warp-plus"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.24"
dotenv = "0.15.0"
inquire = "0.6.2"
rand = "0.8.5"
reqwest = { version = "0.11.17", features = ["json"] }
tokio = { version = "1.28.1", features = ["full"] }
